"""Change relationships

Revision ID: 47ccf92bc9b8
Revises: 47fc62bd004e
Create Date: 2023-11-04 18:52:39.545444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ccf92bc9b8'
down_revision = '47fc62bd004e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
