"""Added products, items and product_items

Revision ID: 47fc62bd004e
Revises: 51fce4d20478
Create Date: 2023-11-04 18:22:52.084389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47fc62bd004e'
down_revision = '51fce4d20478'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
