"""Added products, items and product_items

Revision ID: 51fce4d20478
Revises: 91b06310f562
Create Date: 2023-11-04 18:19:27.070792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51fce4d20478'
down_revision = '91b06310f562'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
