"""Fixed ANOTHER typos in Product Model

Revision ID: 5e47495e8c9b
Revises: e7c19c7e0630
Create Date: 2023-11-04 23:18:46.136810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e47495e8c9b'
down_revision = 'e7c19c7e0630'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('products', 'descritption')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('descritption', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
