"""Changed schemas

Revision ID: 91b06310f562
Revises: de8df61a8d76
Create Date: 2023-11-04 18:15:17.261921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91b06310f562'
down_revision = 'de8df61a8d76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
