"""Changed schemas

Revision ID: de8df61a8d76
Revises: a69eb7d447ed
Create Date: 2023-11-04 18:09:22.435493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8df61a8d76'
down_revision = 'a69eb7d447ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
