"""Fixed typos in Product Model

Revision ID: e7c19c7e0630
Revises: 47ccf92bc9b8
Create Date: 2023-11-04 23:15:48.559661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7c19c7e0630'
down_revision = '47ccf92bc9b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.String(), nullable=True))
    op.drop_column('products', 'categoruy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('categoruy', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('products', 'category')
    # ### end Alembic commands ###
