version: '3.7'
services:
  backend-api:
    container_name: backend-api
    depends_on:
      - database
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    working_dir: /code
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=database 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres 
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  database:
    container_name: database
    image: postgres:11.1
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    